modLoader = "javafml"
loaderVersion = "[42,)"
license = "ARR"

[[mods]]
modId="lychee"
version="${file.jarVersion}"
displayName="Lychee Tweaker"
authors="Snownee"
credits="MikhailTapio"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lychee"
description="Data-driven in-world crafting"
logoFile="logo.png"

[[dependencies.lychee]]
    modId="kiwi"
    mandatory=false
    versionRange="[8,9)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lychee]]
    modId="kubejs"
    mandatory=false
    versionRange="[1902.6.1,)"
    ordering="NONE"
    side="BOTH"

[modproperties.lychee]
    catalogueItemIcon="minecraft:crafting_table" #Support for Catalogue mod
