modLoader = "javafml"
loaderVersion = "[42,)"
license = "ARR"

[[mods]]
modId="lychee"
version="${file.jarVersion}"
displayName="Lychee Tweaker"
authors="Snownee"
credits="MikhailTapio"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lychee"
description="Data-driven in-world crafting"
logoFile="logo.png"

[[dependencies.lychee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lychee]]
    modId="kiwi"
    mandatory=false
    versionRange="[11.1.1,12)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lychee]]
    modId="kubejs"
    mandatory=false
    versionRange="[2001,2002)"
    ordering="NONE"
    side="BOTH"

[modproperties.lychee]
    catalogueItemIcon="minecraft:crafting_table" #Support for Catalogue mod
