modLoader = "javafml"
loaderVersion = "[42,)"
license = "ARR"

[[mods]]
modId="lychee"
version="${file.jarVersion}"
displayName="Lychee Tweaker"
authors="Snownee, MikhailTapio"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lychee"
description="In-World Crafting"

[[dependencies.lychee]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lychee]]
    modId="kubejs"
    mandatory=false
    versionRange="[1902.6.1,)"
    ordering="NONE"
    side="BOTH"

[modproperties.lychee]
    catalogueItemIcon="minecraft:crafting_table" #Support for Catalogue mod
