modLoader = "javafml"
loaderVersion = "*"
license = "ARR"

[[mods]]
modId = "lychee"
version = "${file.jarVersion}"
displayName = "Lychee Tweaker"
authors = "Snownee"
credits = "SettingDust, MikhailTapio"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/lychee"
description = "Data-driven in-world crafting"
logoFile = "logo.png"

[[mixins]]
config = "lychee.mixins.json"

[[dependencies.lychee]]
modId = "minecraft"
versionRange = "[1.21,1.21.2)"

[[dependencies.lychee]]
modId = "kiwi"
versionRange = "[15.3.1, )"

[[dependencies.lychee]]
modId = "jei"
versionRange = "[19.21, )"
type = "optional"

[modproperties.lychee]
catalogueItemIcon = "minecraft:crafting_table" #Support for Catalogue mod